import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs"

import { ThemeProvider } from "@/components/ui/theme-provider"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/components/sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`} 
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <header className="flex justify-end items-center h-16 px-4 gap-4 border-b border-border bg-background">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-primary text-primary-foreground rounded-full font-medium h-10 px-5">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>

              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>

            {/* Sidebar + Content */}
            <SidebarProvider>
              <div className="flex h-[calc(100vh-4rem)] w-full bg-background">
                <AppSidebar />

                {/* IMPORTANT: use SidebarInset */}
                <SidebarInset className="flex-1 p-6 bg-background text-foreground">
                  {children}
                </SidebarInset>
              </div>
            </SidebarProvider>

          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
